/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as TakeawayRouteImport } from './routes/takeaway'
import { Route as StartOrderTableIdRouteImport } from './routes/start-order.$tableId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TakeawayRoute = TakeawayRouteImport.update({
  id: '/takeaway',
  path: '/takeaway',
  getParentRoute: () => rootRouteImport,
} as any)
const StartOrderTableIdRoute = StartOrderTableIdRouteImport.update({
  id: '/start-order/$tableId',
  path: '/start-order/$tableId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/takeaway': typeof TakeawayRoute
  '/start-order/$tableId': typeof StartOrderTableIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/takeaway': typeof TakeawayRoute
  '/start-order/$tableId': typeof StartOrderTableIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/takeaway': typeof TakeawayRoute
  '/start-order/$tableId': typeof StartOrderTableIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/takeaway' | '/start-order/$tableId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/takeaway' | '/start-order/$tableId'
  id: '__root__' | '/' | '/login' | '/takeaway' | '/start-order/$tableId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  TakeawayRoute: typeof TakeawayRoute
  StartOrderTableIdRoute: typeof StartOrderTableIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/takeaway': {
      id: '/takeaway'
      path: '/takeaway'
      fullPath: '/takeaway'
      preLoaderRoute: typeof TakeawayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start-order/$tableId': {
      id: '/start-order/$tableId'
      path: '/start-order/$tableId'
      fullPath: '/start-order/$tableId'
      preLoaderRoute: typeof StartOrderTableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  TakeawayRoute: TakeawayRoute,
  StartOrderTableIdRoute: StartOrderTableIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
